on:
  pull_request:

name: Pull Request Checks

jobs:
  commit-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install gitlint
      - run: |
          gitlint \
            -c general.ignore-fixup-commits=false \
            -c general.ignore-fixup-amend-commits=false \
            -c general.ignore-squash-commits=false \
            --contrib contrib-body-requires-signed-off-by,contrib-disallow-cleanup-commits \
            --commits "$(git merge-base origin/master HEAD)..HEAD"
